language: python
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE threatkb_test;'
python:
  - "2.7"
install:
  - "pip install nose"
  - "pip install -r requirements.txt"
script:
  - SQL_PASSWORD= nosetests tests
